export function createAnnotationState() {
  return {
    store: {
      threads: [],
      easyEdits: [],
      assets: [],
      localAssets: [],
    },
    selectedElement: null,
    selectedElementPath: '',
    selectedElementRef: '',
    activeThreadId: '',
    activeMessageId: '',
    activeEditId: '',
    expandedThreadId: '',
    activeFloatingThreadId: '',
    floatingThreadAnchor: null,
    latestSavedEditsUpdatedAt: null,
    latestSelfSavedEditsHash: '',
    latestSelfSavedEditsCount: 0,
    pendingRemoteEditsSnapshot: null,
    hasLoadedInitialEditsSnapshot: false,
    latestRemoteCollabSnapshot: null,
    floatingUiFrameId: null,
    threadTargetCache: new Map(),
    mainClickHandler: null,
    layerClickHandler: null,
    blockHoverHandler: null,
    blockHoverLeaveHandler: null,
    hoveredBlockEl: null,
    activityFilter: 'all',
    markupsHidden: false,
    panelClickHandler: null,
    panelInputHandler: null,
    panelKeydownHandler: null,
    panelFocusoutHandler: null,
    panelChangeHandler: null,
    inlineAssetsToggleClickHandler: null,
    documentClickHandler: null,
    windowResizeHandler: null,
    mainScrollHandler: null,
    canvasRefreshBarClickHandler: null,
  };
}

export function createAnnotationUI() {
  return {
    mainEl: null,
    layerEl: null,
    popupEl: null,
    panelEl: null,
    panelListEl: null,
    threadEl: null,
    topbarEl: null,
    presenceEl: null,
    workspaceTitleEl: null,
    commentsBtnEl: null,
    activityBtnEl: null,
    canvasRefreshBarEl: null,
    inlineCommentsToggleEl: null,
    annotationMode: 'comments',
    assetSelectMode: false,
    assetSelectHandler: null,
    appliedAssets: new Map(),
  };
}
